# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal, TypeAlias

__all__ = ["TopicEnum"]

TopicEnum: TypeAlias = Literal[
    "ai",
    "ai_agents",
    "base",
    "bitcoin",
    "crypto",
    "dats",
    "defi",
    "ethereum",
    "hyperliquid",
    "machine_learning",
    "macro",
    "on_chain_whale",
    "perps",
    "ripple",
    "rwa",
    "solana",
    "tech",
    "token_listings",
    "virtuals",
    "geopolitics",
    "politics_us",
    "defense",
    "sanctions_trade",
    "equities",
    "rates_fx",
    "commodities",
    "banking_reg",
    "energy",
    "cyber",
    "semiconductors",
    "biotech",
    "logistics",
    "critical_minerals",
    "telecom",
    "region_mena",
    "region_europe",
    "region_asiapac",
    "region_latam",
    "region_africa",
    "region_namerica",
]
